#  This file is part of HLA - Horizon Line Algorithm implementation.
#
#  Copyright (C) 2010  Vladimir Rutsky <altsysrq@gmail.com>
#
#  HLA is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  HLA is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with HLA.  If not, see <http://www.gnu.org/licenses/>.

Import('env')

env['Gch'] = env.Gch('precompiled.hpp')[0]

cflags = "-W -Wall"

X11PATH = "/usr/X11R6"
CIMG_DEBUG_CFLAGS = "-Dcimg_verbosity=3 -Dcimg_strict_warnings"
CIMG_VT100_CFLAGS = "-Dcimg_use_vt100"
CIMG_OPENMP_CFLAGS = "-Dcimg_use_openmp -fopenmp"
CIMG_X11_CFLAGS = "-I" + X11PATH + "/include"

cflags += " " + str(" ").join([CIMG_DEBUG_CFLAGS, CIMG_VT100_CFLAGS, CIMG_OPENMP_CFLAGS])

cflags += " -ICImg -Ieigen2"

env['CPPFLAGS'] = cflags

libs = Split("pthread X11")
libs_path = X11PATH + "/lib"

cpp_path = "."

source_files = Glob("*.cpp")

env.ParseConfig("fltk-config --cxxflags --ldflags")
#env.ParseConfig("fltk-config --ldflags")

env.Program(
    target="hla",
    source=source_files,
    CPPPATH=cpp_path,
    #CCFLAGS=cflags,
    #LIBS=libs,
    #LIBSPATH=libs_path
    )
